server:
  port: 7500
spring:
  application:
    name: ecommerce-multivendor

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_app
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
